image: 
  name: helterpitanga/terraformansible:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
    - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'

cache:
  paths:
    - .terraform

before_script:
  - terraform --version
  - terraform init

stages:
  - init
  - plan
  - apply
  - time
  - master
  - workers

terraform_init:
  stage: init    
  script:
    - terraform init
  after_script:
    - echo "Inicializado com sucesso"

terraform_plan:
  stage: plan
  needs: 
    - terraform_init
  script:
      - terraform plan 
  after_script:
      - echo "plano rodado com sucesso"

terraform_apply:
  stage: apply
  needs: 
    - terraform_plan
  script:
      - terraform apply -auto-approve
  after_script:
      - echo "Apply rodado com sucesso"

time_for_running_stage_instances:
  stage: time
  needs: 
    - terraform_apply
  script:
      - sleep 2m

ansible_master:
  stage: master
  needs:
    - time_for_running_stage_instances
  script:
    - mkdir -p ~/.ssh/
    - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
    - unset PRIVATE_KEY
    - chmod 600 ~/.ssh/id_rsa
    - ansible-playbook -u ubuntu -i ansible/aws_ec2.yaml  --ssh-common-args='-o StrictHostKeyChecking=no' --private-key ~/.ssh/id_rsa ansible/k8smaster.yml

  
